<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('filament-data-copilot::messages.Intelligent Report') }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; background-color: #f8fafc; margin: 0; padding: 20px; color: #334155; }
        .container { max-width: 600px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .header { text-align: center; border-bottom: 1px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 20px; }
        .header h1 { color: #0f172a; font-size: 20px; margin: 0; }
        .content { font-size: 14px; line-height: 1.6; }
        .content p { margin-bottom: 15px; }
        .report-box { background: #f1f5f9; padding: 15px; border-radius: 6px; margin: 20px 0; }
        .report-box h3 { margin: 0 0 10px 0; font-size: 16px; color: #0f172a; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #64748b; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{{ __('filament-data-copilot::messages.Intelligent Analysis Report') }}</h1>
        </div>
        
        <div class="content">
            <p>{{ __('filament-data-copilot::messages.Hello,') }}</p>
            <p>{{ __('filament-data-copilot::messages.Please find attached the requested report from our platform.') }}</p>
            
            <div class="report-box">
                <h3>{{ $report->title ?? __('filament-data-copilot::messages.Data Analysis') }}</h3>
                @if($report->description)
                    <div>{!! \Illuminate\Support\Str::markdown($report->description) !!}</div>
                @else
                    <p>{{ __('filament-data-copilot::messages.Report containing the data requested by the instruction:') }} <em>{{ $report->command }}</em></p>
                @endif
            </div>
            
            <p>{{ __('filament-data-copilot::messages.The attached PDF file contains the complete analysis with the updated data generated at the time of this submission.') }}</p>
        </div>
        
        <div class="footer">
            <p>{{ __('filament-data-copilot::messages.This is an automatic email generated by the system.') }}</p>
        </div>
    </div>
</body>
</html>
